#ifndef KEYBOARDS_CHIBIOS_TEST_STM32_L476_ONEKEY_CONFIG_H_
#define KEYBOARDS_CHIBIOS_TEST_STM32_L476_ONEKEY_CONFIG_H_

#include "../config.h"
#undef NKRO_ENABLE

#endif /* KEYBOARDS_CHIBIOS_TEST_STM32_L476_ONEKEY_CONFIG_H_ */
